# Generated by Django 4.1.7 on 2023-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='desc',
            field=models.CharField(max_length=1300),
        ),
    ]
