# Generated by Django 4.1.7 on 2023-04-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_doctor_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
