# Generated by Django 4.2.6 on 2023-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_medical_staff',
            field=models.BooleanField(default=False),
        ),
    ]
